config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
    validates :name, presence: true
    validates :address, presence: true
    validates :description, presence: true
    validates :price_per_night, presence: true
    validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
    def index
        @flats = Flat.all
    end

    def show
        @flat = Flat.find(params[:id])
    end

    def new
        @flat = Flat.new
    end

    def create
        @flat = Flat.new(flat_params)
        if(@flat.save)
            redirect_to flats_path
        else
            render :new
        end
    end

    def edit
        @flat = Flat.find(params[:id])
    end

    def update
        @flat = Flat.find(params[:id])
        @flat.update(flat_params)
        redirect_to flats_path
    end
    
    def destroy
        @flat = Flat.find(params[:id])
        @flat.destroy
        redirect_to flats_path
    end

    private

    def flat_params
        params.require(:flat).permit(:name, :description, :address, :picture_url, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container" style="width:40%">
        <h1>Edit Flat</h1>
        <%= simple_form_for @flat do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :picture_url %>
        <%= f.input :description %>
        <%= f.input :number_of_guests %>
        <%= f.input :price_per_night %>
        <br/>
        <%= f.submit class:"btn btn-success rounded"%>
        <%= link_to  "Cancel", flat_path, class:"btn btn-danger rounded" %>
        <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
<div class="row">
<%@flats.each do |flat|%>
    <div class="col-3">
        <div class="card" style="width: 20rem;">
            <img src=<%=flat.picture_url%> class="card-img-top" alt="picture">
            <div class="card-body">
                <h4 class="card-title"><%= flat.name%></h4>
                <p class="card-text"><%= flat.address%>
                <br/>
                <i class="fas fa-user-alt" style="margin-left: 10px;"></i><%= flat.number_of_guests%>
                <i class="fas fa-euro-sign" style="margin-left: 10px;"></i><%= flat.price_per_night%></p>
                <%= link_to  "More info", flat_path(flat), class:"btn btn-info" %>
                <%= link_to  "Edit", edit_flat_path(flat), class:"btn btn-warning" %>
                <%= link_to  "Remove", flat_path(flat),method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
            </div>
        </div>
    </div>
    <%end%>
</div>
</div>

app/views/flats/new.html.erb
<div class="container" style="width:40%">
        <h1>Add Flat</h1>
        <%= simple_form_for @flat do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :picture_url %>
        <%= f.input :description %>
        <%= f.input :number_of_guests %>
        <%= f.input :price_per_night %>
        <br/>
        <%= f.submit class:"btn btn-success"%>
        <% end %>
</div>

app/views/flats/show.html.erb
<div style="height:500px;width:100%; background-image:url(<%=@flat.picture_url%>);background-size:cover"></div>
<div class="container" style="position:absolute;top: 490px;left: 200px;">
<div class="row">
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><%= @flat.name %></h5>
                <p class="card-text"><%= @flat.address %></p>
            </div>
        </div><br/>
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">A bit more about this flat...</h5>
            <p class="card-text"><%= @flat.description %></p>
        </div>
        </div>
    </div>
    <div class="col-4">
        <div class="card">
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">From:</span>
                <input type="text" class="form-control" placeholder= <%= Date.today%> aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            </div>
            <div class="input-group mb-3">
                <span class="input-group-text" id="inputGroup-sizing-default">To:</span>
                <input type="text" class="form-control" placeholder= <%= Date.today%> aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            </div>
            <%= link_to  "Book", flat_path(@flat), class:"btn btn-success" %>
        </div>
    </div>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to  "Home", flats_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Add flat", new_flat_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render  "layouts/navbar" %>
    <%= yield %>
  </body>
</html>